name: a1
favicon: null
layout_spectrum: 0.04977400600910187
typography_spectrum: 0.26784341828897595
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2089575263671577
  lightness: 0.2885183705948293
  saturation: 0.05966497561894357
  rhythmicContrast: 0.2817082623951137
purpose: []
